#!/bin/sh

message_file=$1
mode=$2

if [ "$mode" = "" ] || [ "$mode" = "message" ] ; then
  ticket_number=$(git branch | grep "*" | sed -e 's/[^0-9]//g')
  PATTERN=".*#${ticket_number}.*"
  if [ $ticket_number != "" ] && [[ ! $message_file =~ $PATTERN ]]; then
    mv $message_file ${message_file}.tmp
    echo " #$ticket_number $(cat ${message_file}.tmp)" > $message_file
  fi
fi