@startuml class
class GAS {
}

class local {
}


class OutputApiFactory {
  + create(): OutputApi
}

abstract OutputApi {
  + send(text: String): void
}

class Slack
class Console

OutputApi <|-- Slack
OutputApi <|-- Console
OutputApiFactory --> OutputApi

class SlackBot {
  + run()
}

GAS --> SlackBot
GAS --> OutputApiFactory
local --> SlackBot
local --> OutputApiFactory
SlackBot --> Action
Action --> OutputApi

abstract Action {
  + match()
  + do()
}

Action <|-- Debug
Action <|-- Check

class Json {
  + get()
}

@enduml