@startuml class
class GAS {
  + doPost(parameter): void
  + test(): void
}

class OutputApiFactory {
  + create(): OutputApi
}

abstract OutputApi {
  + send(text: String): void
}

class Slack
class Console

OutputApi <|-- Slack
OutputApi <|-- Console
OutputApiFactory --> OutputApi

class SlackBot {
  + run()
}

GAS --> SlackBot
GAS --> OutputApiFactory
SlackBot --> OutputApi

class ActionFactory
abstract Action {
  + match()
  + do()
}
class Start
class Focus
class ShortBreak
class LongBreak
class Stop

ActionFactory --> Action
Action <|-- Start
Action <|-- Focus
Action <|-- ShortBreak
Action <|-- LongBreak
Action <|-- Stop

class Json {
  + get()
}

@enduml